### ISSUE TITLE
MariaDB Aborted Connection

### ISSUE THREAD

**Issue by kkniffin** [roombelt/roombelt#24] opened 2019-04-16 15:27 UTC
Hello, I am trying to connect this to a MariaDB Docker Container. However, on startup I am receiving the following error on roombelt

roombelt_1  | BLOB/TEXT column 'userId' used in key specification without a key length
db_1        | 2019-04-16 15:24:38 10 [Warning] Aborted connection 10 to db: 'roombelt' user: 'dbuser' host: '192.168.64.3' (Got an error reading communication packets)
db_1        | 2019-04-16 15:24:38 9 [Warning] Aborted connection 9 to db: 'roombelt' user: 'dbuser' host: '192.168.64.3' (Got an error reading communication packets)

I have the environment variable for the roombelt docker container set to: 

DATABASE_URL=mysql://dbuser:dbpass@db:3306/roombelt

Any ideas?

**Comment by ziolko** [comment] 2019-04-16 20:07
@kkniffin I've just pushed a new Docker image that contains a fix for this issue (v 1.0.5). Please try it and let me know how it works.

BTW I run PostgreSQL on the production server and this is what I recommend for On-Premises as well.

**Comment by kkniffin** [comment] 2019-04-17 15:13
@ziolko , I think that did the trick. One other non-related question. On the admin consent screen that is prompted when you first sign into the portal, does that require me to check the box for full consent for the organization or just the user I am signed in with? I am running into an issue where when I click find a room, and then select 15mins for example on the room I get "an error occurred" retry/cancel

**Comment by ziolko** [comment] 2019-04-17 20:07
@kkniffin Do you use Google Calendar or Office365? Also, is there any error message in docker console or it fails silently?

You can also try to do the same at app.roombelt.com just to confirm if this is a configuration issue or a bug in the product.

**Comment by kkniffin** [comment] 2019-04-18 14:14
@ziolko This is for 0365.

The only thing in docker console when I hit the button to book as well as to retry is:

roombelt_1  | DEBUG Device ID <id>
roombelt_1  | [object Object]

The website shows:

![Screenshot_2019-04-18_10-10-19](https://user-images.githubusercontent.com/15834993/56366964-3e670780-61c2-11e9-8df7-572cdfadfceb.png)

Permissions for the App registration show:
![Screenshot_2019-04-18_10-12-28](https://user-images.githubusercontent.com/15834993/56367149-9c93ea80-61c2-11e9-9aa1-5d6f528a7a52.png)

**Comment by kkniffin** [comment] 2019-04-18 17:18
@ziolko So apparently in playing around with this it has something to do with room delegation. Several of our rooms require delegate approval before they are allowed to be booked. As a test I removed this on the room I was testing and it seemed to work. I guess the fact that having delegation on the room request and having the request initially be tentative before being accepted it causing an issue?

**Comment by ziolko** [comment] 2019-04-18 17:48
@kkniffin That's a great finding. I will investigate a workaround for delegated approval today and update you.

**Comment by ziolko** [comment] 2019-04-18 20:13
Unfortunately, I can't reproduce this issue in my environment. I've deployed a new version of Roombelt (1.0.6) that should log more details regarding this issue. @kkniffin can you try the newest version and share new log entries?

**Comment by kkniffin** [comment] 2019-04-18 20:54
@ziolko Sorry false alarm I guess on my end. It apparently is working fine now. I must have not let enough time lapse between hitting the "grant admin consent for...." button in our app registration. I tested out on another room with delegation enabled and it seems to work fine. 

Couple things I noticed that I will just throw out for what its worth and feedback:

1. With the delegation, would there be any way of not having the booking show on the room device until it is approved by the delegation admin or perhaps have it show as pending approval? I tested by sending an email, received tentative but the device shows it was occupied as though it was approved? I could see a situation where i send an email that will ultimately be disapproved, however someone goes to the room and it shows occupied? Probably not a big deal and would rarely happen but just a idea.

2. Not sure how it would be done, of if it even makes sense to do. Is there anyway to prevent someone from ending a meeting that wasn't initiated on a room device? An example I am seeing that might occur in the organization is I book a room via email, then another person goes to the room, ends my meeting? Perhaps when a meeting is put in via a in-room device it can be somehow flagged so that only it can be cancelled but meetings booked via email can't be cancelled?

I really appreciate your help and if you would prefer I open separate tickets for tracking purposes just let me know.

**Comment by ziolko** [comment] 2019-04-19 21:21
@kkniffin, I am glad that the issue is gone now. 

I will be happy to understand your use case better. While the requested features seem reasonable I feel I am missing something regarding the way you'd like to use Roombelt.

I will close this issue, but please reach me at mateusz@roombelt.com to discuss your feedback.

Thanks,
Mateusz

**Closed by ziolko** 2019-04-19 21:21 UTC
